<h1>Mon espace</h1>

<section class="flex-around">
    <article>
        <form class="updateUser card-body" action='./index.php?page=dashboardUser' method="POST" enctype="multipart/form-data">

            <?php require_once './src/views/partials/infoUser.phtml' ?>

        </form>
    </article>

    <article>
        <?php require_once './src/views/partials/arrayTournament.phtml' ?>
    </article>
</section>