<h1>Mon espace</h1>

<div class="flex-between-top">
    <section class="flex-column border-screen bigImg position-sticky">
        <a class="btn btn-info" href="#userProfilDashboard">Mon espace</a>
        <a class="btn btn-info" href="#tournamentOnDashboard">Tournois à venir</a>
    </section>
    <section class="flex-around-wrap border-screen">

        <article id="userProfilDashboard">
            <form class="updateUser card-body" action='./index.php?page=dashboardUser' method="POST" enctype="multipart/form-data">

                <?php require_once './src/views/partials/infoUser.phtml' ?>

            </form>
        </article>

        <article id="tournamentOnDashboard">
            <?php require_once './src/views/partials/arrayTournament.phtml' ?>
        </article>
    </section>