<h1>Tableau de bord Administrateur</h1>

<h3>
    <a class="btn btn-success" href="#userProfilDashboard">adminProfil</a>
    <a class="btn btn-success" href="#userListDashboard">usersList</a>
    <a class="btn btn-success" href="#tournamentOnDashboard">tournamentOn</a>
    <a class="btn btn-success">Structure des tournois</a>
    <a class="btn btn-success">Valeur des jetons</a>
    <a class="btn btn-success">Accès aux commentaires</a>
</h3>
<section class="flex-around-wrap border-screen">
    <!-- <article>
    </article> -->
    <article id="userProfilDashboard">
        <?php require_once './src/views/partials/infoUser.phtml' ?>
    </article>
    <article id="userListDashboard">
        <?php require_once './src/views/partials/usersList.phtml' ?>
    </article>
    <article id="tournamentOnDashboard">
        <!-- <h2>LISTE DES TOURNOIS DISPONIBLES</h2> -->
        <?php require_once './src/views/partials/arrayTournament.phtml' ?>
    </article>
</section>