<section class='grid col3'>
    <article class="item btn-success">
        <p>Heure actuelle</p>
        <p id='actualTime'></p>
    </article>
    <article class="item btn-info portrait3">
        <p>Prochain niveau dans</p>
        <p>0:20:00</p>
    </article>
    <article class="item btn-alert portrait2">
        <p>Valeur des jetons</p>
        <div><img src="./asset/images/token/white.png" alt="white token" class="small-token">5</div>
        <div><img src="./asset/images/token/red.png" alt="red token" class="small-token">10</div>
        <div><img src="./asset/images/token/green.png" alt="green token" class="small-token">25</div>
        <div><img src="./asset/images/token/blue.png" alt="blue token" class="small-token">50</div>
        <div><img src="./asset/images/token/black.png" alt="black token" class="small-token">100</div>
        <div><img src="./asset/images/token/yellow.png" alt="yellow token" class="small-token">500</div>
        <div><img src="./asset/images/token/rose.png" alt="rose token" class="small-token">1000</div>
        <div><img src="./asset/images/token/brown.png" alt="brown token" class="small-token">5000</div>
    </article>

    <article class="item btn-success">
        <p>Prochaine pause dans</p>
        <p>0:20:00</p>
    </article>
    <article class="item btn-info">
        <p>Niveau : 5</p>
    </article>
    <article class="item btn-alert">
        <p>Tapis moyen</p>
        <p>102000</p>
    </article>
</section>
<section class='grid col3'>
    <article class="item btn-info">
        <p>Joueurs inscrits : 17</p>
    </article>
    <article class="item btn-alert">
        <p>Blinds : 100 / 200</p>
    </article>
    <article class="item btn-success medium">
        <p>Prochaine pause à</p>
        <p>16:30</p>
    </article>
</section>
</section>
<section class='grid col4'>
    <article class="item btn-info">
        <p>Joueurs restants : 11</p>
    </article>
    <article class="item btn-alert">
        <p>Prochaines blinds : 150 / 300</p>
    </article>
    <article class="item btn btn-danger medium">
        <p>Sortir un joueur</p>
    </article>
    <article class="item btn btn-info medium">
        <p>Lancer le chrono</p>
    </article>
</section>