<h1>JEU</h1>

<div class='grid c1'>
    <p class="item btn btn-success">Heure actuelle</p>
    <p class="item btn btn-info">
        <!-- <?php require './src/views/partials/flip.phtml'; ?> -->
        <?= date('D, d M Y H:i:s') ?>
    </p>
    <p class="item btn btn-alert">Valeur des jetons</p>

    <p class="item btn btn-success">Heure actuelle</p>
    <p class="item btn btn-info">
        <!-- <?php require './src/views/partials/flip.phtml'; ?> -->
        <?= date('D, d M Y H:i:s') ?>
    </p>
    <p class="item btn btn-alert">Valeur des jetons</p>
</div>
