<section class="fond-Table border-screen">
    <a href="./index.php?page=game"><img src="./asset/images/token/dealer.png" alt="dealer" class="dealer"></a>
    <!-- <p>Accès à la table de jeu</p> -->
    <div class="flex-between">
        <p>
            <a href="./index.php?page=players&action=display"><img src="./asset/images/carte-R.jpg" alt="carte">Players</a>
        </p>
        <p>
            <a href="./index.php?page=tables"><img src="./asset/images/carte-R.jpg" alt="carte" role="button">Tables</a>
        </p>
        <p>
            <a href=""><img src="./asset/images/carte-R.jpg" alt="carte">Structure</a>
        </p>
        <p>
            <a href=""><img src="./asset/images/carte-R.jpg" alt="carte">Classement</a>
        </p>
        <p>
            <a href=""><img src="./asset/images/carte-R.jpg" alt="carte">Comments</a>
        </p>
    </div>
</section>