<section class="fond-Table">
    <img src="./asset/images/token/dealer.png" alt="dealer" class="dealer">
    <!-- <p>Accès à la table de jeu</p> -->
    <div class="flex-between">
        <p>
            <a href="./index.php?page=players"><img src="./asset/images/carte-R.jpg" alt="carte">Players</a>
        </p>
        <p>
            <a href="./index.php?page=tables"><img src="./asset/images/carte-R.jpg" alt="carte" role="button">Tables</a>
        </p>
        <p>
            <a href="#"><img src="./asset/images/carte-R.jpg" alt="carte">Structure</a>
        </p>
        <p>
            <a href="#"><img src="./asset/images/carte-R.jpg" alt="carte">Classement</a>
        </p>
        <p>
            <a href="#"><img src="./asset/images/carte-R.jpg" alt="carte">Comments</a>
        </p>
    </div>
</section>