<h1>Inscription</h1>

<!-- <section>
    <img src="./asset/images/Token-70.png" alt="table" width="800px">
</section> -->

<section class="flex-column border-screen">
    <h2 class="from-left">Prêt à vous inscrire ?</h2>
    <article class="btn btn-success">
        <button type="text">Déjà inscrit sur Poker Hold'hem Tournament Poker ?<a href="./index.php?page=login" class="btn btn-alert">Connexion</a></button>
    </article>

    <form class="createUser card-body" action='./index.php?page=inscription' method="POST" enctype="multipart/form-data">
        <!-- <form class="card-body" id="createUser"> -->
        <fieldset>
            <div>
                <input type="hidden" name="action" value="persist">
                <label for="nickname" class="btn-info">Pseudonyme *</label>
                <div class="card-text">
                    <span class="card-puce"><i class="fas fa-ghost"></i></span>
                    <input type="text" class="card-input" name="nickname" placeholder="Pseudonyme" required autofocus>
                </div>
            </div>
            <div>
                <label for="lastname" class="btn-info">Nom</label>
                <div class="card-text">
                    <span class="card-puce"><i class="fas fa-user"></i></span>
                    <input type="text" class="card-input" name="lastname" placeholder="Nom">
                </div>
            </div>
            <div>
                <label for="firstname" class="btn-info">Prénom</label>
                <div class="card-text">
                    <span class="card-puce"><i class="fas fa-user"></i></span>
                    <input type="text" class="card-input" name="firstname" placeholder="Prénom">
                </div>
            </div>
            <div>
                <label for="email" class="btn-info">Adresse mail *</label>
                <div class="card-text">
                    <span class="card-puce"><i class="fas fa-at"></i></span>
                    <input type="text" class="card-input" name="email" placeholder="Adresse mail" required>
                </div>
            </div>
            <div>
                <label for="password" class="btn-info">Mot de passe *</label>
                <div class="card-text">
                    <span class="card-puce"><i class="fas fa-key"></i></span>
                    <input type="password" class="card-input" name="password" placeholder="Mot de passe" required>
                    <span class="small btn-info-inv">Minimum 8 caract dont 1 minuscule, 1 majuscule, 1 chiffre et 1 caract spécial</span>
                </div>
            </div>
            <div>
                <label for="avatar" class="btn-info">Avatar</label>
                <div class="card-text">
                    <span class="card-puce"><i class="fas fa-camera"></i></span>
                    <input type="file" accept=".jpg, .jpeg, .png, .bmp" class="card-input btn-info-inv" name="avatar">
                </div>
            </div>
            <p class="small text-left messageGrey">* : information obligatoire</p>
            <button type="submit" class="btn btn-info">Valider la création du compte</button>
        </fieldset>
    </form>
</section>