<h1>Inscription</h1>

<!-- <section>
    <img src="./asset/images/Token-70.png" alt="table" width="800px">
</section> -->

<section class="flex-column">
    <h2 class="from-left">Prêt à vous inscrire ?</h2>
    <button type="text">Déjà inscrit sur Poker Hold'hem Tournament Poker ?<a href="./index.php?page=login" class="btn btn-alert">Connexion</a></button>
    <!-- <form class="card-body" action='./src/services/ajaxLog.php' method="POST" id="createUser"> -->
    <form class="card-body" id="createUser">
        <!-- <form class="card-body" id="createUser" method="post" enctype="multipart/form-data"> -->
        <fieldset>
            <div>
                <input type="hidden" name="action" value="insert">
                <span class="errors"></span>
                <label for="nickname" class="btn-info">Pseudonyme *</label>
                <div class="card-text">
                    <span class="card-puce"><i class="fab fa-napster"></i></span>
                    <input type="text" class="card-input" name="nickname" placeholder="Pseudonyme" required autofocus>
                </div>
            </div>
            <div>
                <label for="lastname" class="btn-info">Nom</label>
                <div class="card-text">
                    <span class="card-puce"><i class="fas fa-user"></i></span>
                    <input type="text" class="card-input" name="lastname" placeholder="Nom">
                </div>
            </div>
            <div>
                <label for="firstname" class="btn-info">Prénom</label>
                <div class="card-text">
                    <span class="card-puce"><i class="fas fa-user"></i></span>
                    <input type="text" class="card-input" name="firstname" placeholder="Prénom">
                </div>
            </div>
            <div>
                <label for="email" class="btn-info">Adresse mail *</label>
                <div class="card-text">
                    <span class="card-puce"><i class="fas fa-at"></i></span>
                    <input type="text" class="card-input" name="email" placeholder="Adresse mail" required>
                </div>
            </div>
            <div>
                <label for="password" class="btn-info">Mot de passe *</label>
                <div class="card-text">
                    <span class="card-puce"><i class="fas fa-key"></i></span>
                    <input type="text" class="card-input" name="password" placeholder="Mot de passe" required>
                    <span class="small btn-info-inv">Minimum 8 caractères dont 1 majuscule, 1 chiffre et 1 caractère spécial</span>
                </div>
            </div>
            <div>
                <label for="avatar" class="btn-info">Avatar</label>
                <div class="card-text">
                    <span class="card-puce"><i class="fas fa-camera"></i></span>
                    <input type="file" accept=".jpg, .jpeg, .png, .bmp" class="card-input btn-info-inv" name="avatar" aria-describedby="fileHelp">
                </div>
            </div>
            <button type="submit" class="btn btn-info">Valider la création de compte</button>
        </fieldset>
    </form>
</section>