<h1>Login</h1>

<section class="flex-column">
    <h2 class="from-left">Connectez-vous</h2>

    <form class="auth card-body" action='./index.php?page=login' method="POST">
        <fieldset>
            <input type="hidden" name="action" value="auth">
            <div class="card-text">
                <label for="email" class="btn-info">Adresse mail *</label>
                <span class="card-puce"><i class="fas fa-at"></i></span>
                <input type="text" class="card-input" name="email" placeholder="Adresse mail" required autofocus>
            </div>
            <div class="card-text">
                <label for="password" class="btn-info">Mot de passe *</label>
                <span class="card-puce"><i class="fas fa-key"></i></span>
                <input type="password" class="card-input" name="password" placeholder="Mot de passe" required>
            </div>
            <p class="small text-left messageGrey">* : information obligatoire</p>
            <button type="submit" class="btn btn-info">Connexion</button>
        </fieldset>
    </form>
</section>
<section class="flex-column">
    <fieldset class="alert-alert">
        <p>Vous ne possédez pas encore de compte sur Poker Hold'hem Tournament Poker ?</p>
        <button type="text" class="btn btn-info"><a href="./index.php?page=inscription">Inscrivez-vous</a></button>
    </fieldset>
</section>