
<h1>Login</h1>

<!-- <section>
    <img src="./asset/images/Token-70.png" alt="table" width="800px">
</section> -->

<section class="flex-column">
    <h2 class="from-left">Connectez-vous</h2>
    <span class="errors"></span>
    <!-- <form class="card-body" action='./src/services/ajaxLog.php' method="POST" id="auth"> -->
    <form class="card-body" id="auth">
        <input type="hidden" name="action" value="auth">
        <div class="card-text">
            <span class="card-puce"><i class="fas fa-at"></i></span>
            <input type="text" class="card-input" name="email" placeholder="Adresse mail" required autofocus>
        </div>
        <div class="card-text">
            <span class="card-puce"><i class="fas fa-key"></i></span>
            <input type="text" class="card-input" name="password" placeholder="Mot de passe" required>
        </div>
        <button type="submit" class="btn btn-info">Connexion</button>
    </form>
</section>
<section>
    <button type="text" class="btn btn-alert">
        <bold>Mot de passe oublié ?</bold>
    </button>
    <fieldset>
        <p>Vous ne possédez pas encore de compte sur Poker Hold'hem Tournament Poker ?</p>
        <button type="text" class="btn btn-info"><a href="./index.php?page=inscription">Inscription</a></button>
    </fieldset>
</section>