<h1><a href="https://fr.pokernews.com/dictionnaire-poker/" target="_blank">Les règles du poker</a></h1>

<section class="">
  <h1 class="">Dictionnaire Poker- Lexique des termes du poker</h1>
  <div class="">
    <p>N'avez vous pas serré les dents d'angoisse ou d'agacement devant les termes "<a href="https://fr.pokernews.com/dictionnaire-poker/hand-for-hand.htm">Hand for Hand</a>", "<a href="/dictionnaire-poker/joueur-nit.htm">Nit</a>", "<a href="https://fr.pokernews.com/dictionnaire-poker/w-sd.htm">W$SD</a>", "<a href="https://fr.pokernews.com/dictionnaire-poker/cutoff-position.htm">Cutoff</a>" ou encore "<a href="https://fr.pokernews.com/dictionnaire-poker/hijack-position.htm">HiJack</a>" ? "<a href="https://fr.pokernews.com/dictionnaire-poker/main-homme-mort.htm">Dead Man's Hand</a>" excite votre curiosité de joueur ? Vous aussi vous désirez y aller de votre "DonkBet", "Rigged", "Bodonkey" et autres "Spew" ? Perdu entre les tournois EPT, WPT, WSOP et autres NAPT ? Le dictionnaire du Poker Pokernews est là pour vous aider avec une base de donnée de définitions.</p>
    <h2>Dictionnaire du poker en ligne et live</h2>
    <p>Depuis l'avènement du poker en ligne début 2000, le jeu est emprunt de mots étranges et d'expressions très précises que les joueurs avertis utilisent par soucis de concision et de précision, mais aussi par simple mimétisme. Le poker a désormais son propre vocabulaire, son jargon et il est parfois embarrassant d'admettre que l'on ne comprend pas forcément de quoi il est question. Le poker live n'est pas non plus exempt de vocabulaire exotique puisque la majeure partie des termes techniques proviennent de l'anglais américain. La rédaction Pokernews rassemble donc le plus de termes possibles en essayant de les expliquer au sein d'un dictionnaire en ligne du poker. Vous pouvez également participer à l'ajout de défitions</p>
    <h2>Définitions de base du joueur débutant</h2>
    <p>Le joueur de poker qui débute au poker ne peut ignorer les termes suivant : <br>
      <b>Mise (bet)</b> : mettre ses jetons dans le pot.<br>
      <b>Call</b> : simplement suivre une mise sans relancer.<br>
      <b>Check</b> : parole, ne pas miser lorsque la situation est possible.<br>
      <b>Raise</b> : une relance, mise supérieur à la précédente mise.<br>
      <b>Board</b> : cartes visibles sur la table par opposition aux cartes privées des joueurs.<br>
      <b>Flop</b> : trois premières cartes visibles posée par le croupier.<br>
      <b>Turn</b> : quatrième carte posée par le croupier.<br>
      <b>River</b> : cinquième carte posée par le croupier.<br>
      et bien sûr... <b><a href="https://fr.pokernews.com/dictionnaire-poker/fish.htm">Fish</a></b> !
    </p>
  </div>

</section>