<h1><a href="https://fr.pokernews.com/dictionnaire-poker/" target="_blank">Les règles du poker</a></h1>

<section class="border-screen">
  <h1 class="">Règles officielles du poker texas holdem</h1>
  <p>https://pairedas.com/regles-du-poker-officielles/</p>
  <div class="">
    <p><strong>Le Texas Hold ‘Em (ou Texas Holdem) est la principale variante du poker jouée dans de monde dans les casinos ou sur internet.</strong></p>
    <p>Pour gagner au Texas Hold’em, vous devez :

      avoir la meilleure main de cinq cartes lors du dernier tour de mise
      ou “bluffer” pour convaincre les autres joueurs de céder à votre mise et de se coucher.


      Dans ce guide du Texas Hold’em pour débutants, vous apprendrez à jouer au poker, à comprendre les règles de base, les types de mises et les conseils. Le Texas Hold’em est facile à apprendre et les règles sont simples, ce qui vous permet de jouer aux tables en un rien de temps.

      Comme le dit un célébre joueur de poker “5 minutes pour l’apprendre, une vie pour le maîtriser”</p>
    <h2>Comment se déroule une partie de Texas Hold'em</h2>
    <p>Le Texas Hold’em utilise un jeu standard de 52 cartes à jouer. Chaque joueur reçoit deux cartes, une à la fois, face cachée. Ces cartes sont appelées “hole cards”, “down cards” ou “pocket cards”. Il y a un premier tour d’enchères. Trois cartes communes sont ensuite distribuées au milieu de la table, face visible. Elles sont connues collectivement sous le nom de “le flop”. Ce tour est suivi par le deuxième tour d’enchères. Une quatrième carte commune est ensuite distribuée face visible. C’est ce que l’on appelle “la turn”. Il est suivi d’un troisième tour de mise. Une cinquième et dernière carte commune est distribuée. C’est ce qu’on appelle “la river”. Un cinquième et dernier tour de mise suit.</p>
    <h2>Nombre de joueurs à table</h2>
    <p>Le nombre de joueurs autour d’une table de poker n’est pas fixe, il peut aller de 2 (tête-à-tête), jusqu’à 10 par table dans les tournois ou parties en ligne. Cette donnée n’est pas sans importance et doit influencer la manière de jouer vos cartes.
    </p>
    <h2>Avant le Flop - Pré flop</h2>
    <p>Les joueurs ont la possibilité de jouer au jeu après avoir vu leurs cartes fermées. Seul un joueur agissant à la fois pour miser dans le jeu prend l’une des options disponibles (suivre, relancer ou se coucher) en fonction de la force des cartes fermées. Le joueur peut également miser tous ses jetons et faire tapis à tout moment au cours d’un tour de mise. Les paris commencent avec le joueur à gauche de la grosse blind et se poursuivent dans le sens des aiguilles d’une montre jusqu’à ce que tous les joueurs de la table aient placé une mise égale.
    </p>
    <h2>Au Flop</h2>
    <p>Une fois que le tour d’enchères pré-flop est terminé au Texas Holdem, 3 cartes sont distribuées face visible sur la table, appelées cartes du Flop. L’action commence avec le joueur actif qui se trouve immédiatement à gauche du bouton. Les joueurs commencent à miser selon le même schéma que le pré-flop en fonction de la force de leur combinaison de 3 cartes flop et de 2 cartes fermées ainsi que de la probabilité de former une meilleure main de poker avec 2 autres cartes encore à distribuer. Le premier joueur à agir en premier dans le tour de flop peut choisir de faire parole (checker) car aucune mise n’a été faite avant lui ou de miser.
    </p>
    <h2>Au tournant - La turn</h2>
    <p>Une seule carte est distribuée face visible sur la table après le tour de mise du flop. La mise est lancée de la même manière que pour les deux tours précédents, en fonction de la nouvelle force de la combinaison des cartes et des probabilités calculées par chaque joueur restant sur la table. L’action commence avec le joueur actif qui se trouve immédiatement à gauche du bouton.
    </p>
    <h2>La rivière - River</h2>
    <p>Lorsque le tour de mise est terminé, la dernière carte distribuée est retournée sur la table, appelée “River”. L’action commence avec le joueur actif qui se trouve immédiatement à gauche du bouton. Les mises progressent de la même manière jusqu’à ce que les autres joueurs actifs aient atteint le même montant ou relance du minimum du double de la mise initiale.
    </p>
    <h2>Abattage</h2>
    <p>Tous les joueurs qui restent dans le jeu montrent leurs cartes après le tour d’enchère terminé. Le joueur ayant la meilleure combinaison de 5 cartes remporte les jetons.

      Le gagnant reçoit l’argent du pot et le bouton du croupier passe au joueur suivant dans le sens des aiguilles d’une montre pour que la nouvelle partie commence. Si plus d’un gagnant émerge sur la base de sa main de poker, le pot est divisé entre eux en conséquence.
    </p>
    <h2>La combinaisons au poker texas holdem</h2>
    <p>
    </p>
    <p>Quinte flush royale

      5 cartes qui se suivent, de la même couleur et qui se termine par l’AS: 10, J, Q, K, A de la même couleur. Une Quinte Flush Royale (en français et la Royal Flush en anglais) est la meilleur combinaison au poker.

      Quinte Flush :

      5 cartes qui se suivent, de la même couleur. En cas d’égalité: la suite la plus haute gagne.

      Carré

      4 cartes de la même valeur et une carte isolée ou « kicker ». En cas d’égalité : le carré le plus haut gagne. Dans les jeux avec cartes communes où les joueurs ont les mêmes carrés, la cinquième carte la plus haute (le « kicker ») l’emporte.

      Full House

      La combinaison est formée de 3 cartes de la même valeur et 2 autres cartes de la même valeur. En cas d’égalité : les trois cartes les plus hautes de la même valeur gagnent le pot. Dans les jeux avec cartes communes où les joueurs ont chacun trois cartes de la même valeur, la paire la plus haute l’emporte.

      Couleur ou flush

      5 cartes de la même couleur. Si plusieurs joueurs ont une couleur (en français et Flush en anglais) , c’est celui qui détient la carte la plus haute, dans la couleur, gagne. Si deux mains ont la même carte haute, on compare la carte de rang inférieur, et ainsi de suite, toujours dans la couleur.

      Suite ou Quinte

      5 cartes qui se suivent. En cas d’égalité : la suite la plus haute gagne. Remarque : l’As peut être utilisé en début ou en fin de suite (c’est la seule carte qui peut avoir double emploi). A, K, Q, J, 10 est la quinte la plus haute (à l’as) ; 5, 4, 3, 2, A est la quinte la plus petite (au 5). En français, on parle de la suite ou de la quinte et en Anglais de la straight.

      Brelan

      3 cartes de la même valeur et 2 autres cartes dépareillées. En cas d’égalité : le brelan le plus haut gagne. Dans les jeux avec cartes communes où les joueurs ont les mêmes brelans, la carte supplémentaire la plus haute et, si nécessaire, la deuxième carte supplémentaire la plus haute l’emporte

      Double paire

      2 cartes de la même valeur et 2 autres cartes de la même valeur, ainsi qu’une carte supplémentaire. En cas d’égalité : la paire la plus haute gagne. Si plusieurs joueurs ont la même paire la plus haute, la deuxième paire la plus haute l’emporte. Si les deux joueurs ont des paires identiques, la carte supplémentaire la plus haute gagne.

      Une paire

      2 cartes de la même valeur. En cas d’égalité : la paire la plus haute gagne. Si plusieurs joueurs ont la même paire, la carte supplémentaire la plus haute et, si nécessaire, les deuxième et troisième cartes supplémentaires les plus hautes peuvent servir à départager les joueurs.

      Carte Haute – Hauteur

      Toute main qui n’entre pas dans les catégories précédentes. En cas d’égalité : la carte la plus haute gagne et si nécessaire, la deuxième carte la plus haute (appelée le « Kicker ») remporte le coup.
    </p>
  </div>

</section>