<section class="border-screen">
  <h1 class="">Règles du poker Texas Hold'hem</h1>
  <div class="text-left btn-info-inv padding-5">
    <p><strong>Le Texas Hold'hem est la principale variante du poker jouée dans de monde dans les casinos ou sur internet.</strong></p>
    <p>Pour gagner au Texas Hold'hem, vous devez :</p>

    <p>- avoir la meilleure main de cinq cartes lors du dernier tour de mise</p>
    <p>- <q>bluffer</q> pour convaincre les autres joueurs de céder à votre mise et de se coucher.</p>
    <p>Le Texas Hold'hem est facile à apprendre et les règles sont simples, ce qui vous permet de jouer aux tables en un rien de temps.</p>

    <p>Comme le dit un célébre joueur de poker <q>5 minutes pour l’apprendre, une vie pour le maîtriser</q></p>
  </div>

  <h2>Comment se déroule une partie de Texas Hold'hem ?</h2>
  <div class="text-left btn-info-inv padding-5">
    <p>Le Texas Hold'hem utilise un jeu standard de 52 cartes à jouer.</p>
    <p>Chaque joueur reçoit deux cartes, une à la fois, face cachée.</p>
    <p>Il y a un premier tour d’enchères. Trois cartes communes sont ensuite distribuées au milieu de la table, face visible. Elles sont connues collectivement sous le nom de <q>le flop</q>.
    </p>
    <p>Ce tour est suivi par le deuxième tour d’enchères. Une quatrième carte commune est ensuite distribuée face visible. C’est ce que l’on appelle <q>la turn</q>.
    </p>
    <p>Il est suivi d’un troisième tour de mise. Une cinquième et dernière carte commune est distribuée. C’est ce qu’on appelle <q>la river</q>. Un cinquième et dernier tour de mise suit.</p>
  </div>

  <h2>Nombre de joueurs à table</h2>
  <div class="text-left btn-info-inv padding-5">
    <p>Le nombre de joueurs autour d’une table de poker n’est pas fixe, il peut aller de 2 (tête-à-tête ou <q>heads'up</q>), jusqu’à 10 par table dans les tournois ou parties en ligne.
    </p>
    <p>Cette donnée n’est pas sans importance et doit influencer la manière de jouer vos cartes.
    </p>
  </div>

  <h2>Avant le Flop - le Pré flop</h2>
  <div class="text-left btn-info-inv padding-5">
    <p>Les joueurs peuvent entrer en jeu après avoir vu leurs cartes fermées.
    </p>
    <p>Chacun leur tour, les joueurs peuvent choisir l’une des options disponibles : <q>suivre, relancer</q> ou <q>se coucher</q>, en fonction de la force des cartes fermées.
    </p>
    <p>Le joueur peut également miser tous ses jetons et faire tapis ou <q>all in</q> à tout moment au cours d’un tour de mise.
    </p>
    <p>Les paris commencent avec le joueur à gauche de la grosse <q>blind</q> et se poursuivent dans le sens des aiguilles d’une montre jusqu’à ce que tous les joueurs de la table aient placé une mise égale.
    </p>
  </div>

  <h2>Au Flop</h2>
  <div class="text-left btn-info-inv padding-5">
    <p>Une fois que le tour d’enchères pré-flop est terminé, 3 cartes sont distribuées face visible sur la table, appelées cartes du Flop.
    </p>
    <p>L’action commence avec le joueur actif qui se trouve immédiatement à gauche du bouton.
    </p>
    <p>Les joueurs commencent à miser selon le même schéma que le pré-flop en fonction de la force de leur combinaison de 3 cartes flop et de 2 cartes fermées ainsi que de la probabilité de former une meilleure main de poker avec 2 autres cartes encore à distribuer.
    </p>
    <p>Le premier joueur à agir dans le tour de flop peut choisir de faire parole <q>checker</q> car aucune mise n’a été faite avant lui ou de miser.
    </p>
  </div>

  <h2>Au tournant - La turn</h2>
  <div class="text-left btn-info-inv padding-5">
    <p>Une seule carte est distribuée face visible sur la table après le tour de mise du flop.
    </p>
    <p>La mise est lancée de la même manière que pour les deux tours précédents, en fonction de la nouvelle force de la combinaison des cartes et des probabilités calculées par chaque joueur restant sur la table.
    </p>
    <p>L’action commence avec le joueur actif qui se trouve immédiatement à gauche du bouton.
    </p>
  </div>

  <h2>La rivière - River</h2>
  <div class="text-left btn-info-inv padding-5">
    <p>Lorsque le tour de mise est terminé, la dernière carte distribuée est retournée sur la table, appelée <q>River</q>.
    </p>
    <p>L’action commence avec le joueur actif qui se trouve immédiatement à gauche du bouton.
    </p>
    <p>Les mises progressent de la même manière jusqu’à ce que les autres joueurs actifs aient atteint le même montant ou relance du minimum du double de la mise initiale.
    </p>
  </div>

  <h2>Abattage</h2>
  <div class="text-left btn-info-inv padding-5">
    <p>Tous les joueurs qui restent dans le jeu montrent leurs cartes après le tour d’enchère terminé.
    </p>
    <p>Le joueur ayant la meilleure combinaison de 5 cartes remporte les jetons.
    </p>

    <p>Le gagnant reçoit l’argent du pot et le bouton du croupier passe au joueur suivant dans le sens des aiguilles d’une montre pour que la nouvelle partie commence.
    </p>
    <p>Si plus d’un gagnant émerge sur la base de sa main de poker, le pot est divisé entre eux en conséquence.
    </p>
  </div>

  <h2>La combinaisons au poker texas Hold'hem</h2>
  <h3>Quinte flush royale</h3>
  <div class="text-left btn-info-inv padding-5">

    <p>5 cartes qui se suivent, de la même couleur et qui se termine par l’AS: 10, J, Q, K, A de la même couleur.</p>
    <p>Une Quinte Flush Royale (en français et la <q>Royal Flush</q> en anglais) est la meilleur combinaison au poker.
    </p>
  </div>

  <h3>Quinte Flush</h3>
  <div class="text-left btn-info-inv padding-5">

    <p>5 cartes qui se suivent, de la même couleur.</p>
    <p>En cas d’égalité: la suite la plus haute gagne.
    </p>
  </div>

  <h3>Carré</h3>
  <div class="text-left btn-info-inv padding-5">

    <p>4 cartes de la même valeur et une carte isolée ou <q>kicker</q>.</p>
    <p>En cas d’égalité : le carré le plus haut gagne. Dans les jeux avec cartes communes où les joueurs ont les mêmes carrés, la cinquième carte la plus haute (le <q>kicker</q>) l’emporte.</p>
  </div>

  <h3>Full House</h3>
  <div class="text-left btn-info-inv padding-5">

    <p>La combinaison est formée de 3 cartes de la même valeur et 2 autres cartes de la même valeur.</p>
    <p>En cas d’égalité : les trois cartes les plus hautes de la même valeur gagnent le pot. Dans les jeux avec cartes communes où les joueurs ont chacun trois cartes de la même valeur, la paire la plus haute l’emporte.
    </p>
  </div>

  <h3>Couleur ou flush</h3>
  <div class="text-left btn-info-inv padding-5">

    <p>5 cartes de la même couleur. Si plusieurs joueurs ont une couleur (en français et <q>Flush</q> en anglais) , c’est celui qui détient la carte la plus haute, dans la couleur, gagne.</p>
    <p>Si deux mains ont la même carte haute, on compare la carte de rang inférieur, et ainsi de suite, toujours dans la couleur.
    </p>
  </div>

  <h3>Suite ou Quinte</h3>
  <div class="text-left btn-info-inv padding-5">

    <p>5 cartes qui se suivent.</p>
    <p>En cas d’égalité : la suite la plus haute gagne. Remarque : l’As peut être utilisé en début ou en fin de suite (c’est la seule carte qui peut avoir double emploi). A, K, Q, J, 10 est la quinte la plus haute (à l’as) ; 5, 4, 3, 2, A est la quinte la plus petite (au 5). En français, on parle de la suite ou de la quinte et en Anglais de la <q>straight</q>.
    </p>
  </div>

  <h3>Brelan</h3>
  <div class="text-left btn-info-inv padding-5">

    <p>3 cartes de la même valeur et 2 autres cartes dépareillées.</p>
    <p>En cas d’égalité : le brelan le plus haut gagne. Dans les jeux avec cartes communes où les joueurs ont les mêmes brelans, la carte supplémentaire la plus haute et, si nécessaire, la deuxième carte supplémentaire la plus haute l’emporte
    </p>
  </div>

  <h3>Double paire</h3>
  <div class="text-left btn-info-inv padding-5">

    <p>2 cartes de la même valeur et 2 autres cartes de la même valeur, ainsi qu’une carte supplémentaire.</p>
    <p>En cas d’égalité : la paire la plus haute gagne. Si plusieurs joueurs ont la même paire la plus haute, la deuxième paire la plus haute l’emporte. Si les deux joueurs ont des paires identiques, la carte supplémentaire la plus haute gagne.
    </p>
  </div>

  <h3>Une paire</h3>
  <div class="text-left btn-info-inv padding-5">

    <p>2 cartes de la même valeur.</p>
    <p>En cas d’égalité : la paire la plus haute gagne. Si plusieurs joueurs ont la même paire, la carte supplémentaire la plus haute et, si nécessaire, les deuxième et troisième cartes supplémentaires les plus hautes peuvent servir à départager les joueurs.
    </p>
  </div>

  <h3>Carte Haute – Hauteur</h3>
  <div class="text-left btn-info-inv padding-5">

    <p>Toute main qui n’entre pas dans les catégories précédentes.</p>
    <p>En cas d’égalité : la carte la plus haute gagne et si nécessaire, la deuxième carte la plus haute (appelée le <q>Kicker</q>) remporte le coup.
    </p>
  </div>

</section>