<table class='array'>
        <?php if ($type === "users") {
            $list = $users;
        } else {
            $list = $players;
        } ?>
    <caption><?= count($list).' : '.$title ?></caption>
    <tr>
        <th>​<input type='checkbox' name='checkboxall[]' value=<?= $type ?>></th>
        <th>​Pseudo</th>
        <th>​Nom</th>
        <th>​Prénom</th> 
        <th>avatar</th>
    </tr> 
</table>
<div class='array-border tab<?= $type ?>List'>
    <table class='array <?= $type ?>'>
        <?php foreach ($list as $user) : { ?>
                <tr>
                    <td><input type='checkbox' name='checkboxuser[]' value=<?= $user['id'] ?>></td>
                    <td class="selectUser <?= $user['id'] ?>"><?= $user['nickName'] ?></td>
                    <td class="selectUser <?= $user['id'] ?>"><?= $user['firstName'] ?></td>
                    <td class="selectUser <?= $user['id'] ?>"><?= $user['lastName'] ?></td>
                    <td><?php if ($user['avatar'] !== "") : { ?>
                                <img src=<?= $user['avatar'] ?> alt='avatar'>
                        <?php }
                                                                endif; ?>
                    </td>
                </tr>
        <?php }
        endforeach; ?>
    </table>
</div>