<!-- Page PLAYER : Affiche le tableau avec le bon titre en fonction de l'appel : User ou Player -->
<!-- Mise à disposition de la session -->
<?php //require_once '../services/session.php'; ?>

<table class='array'> 
    <caption><?= $title ?></caption>
    <tr> 
        <th>​<input type='checkbox' name='checkboxall[]' value=<?= $type ?>></th>
        <th>​Pseudo</th>
        <th>​Nom</th>
        <th>​Prénom</th> 
        <th>avatar</th>
    </tr> 
</table>
<div class='array-border tab<?= $type ?>List'>
    <!-- Emplacement du tableau des users / players -->
    <table class='array <?= $type ?>'>
        <?php foreach ($_SESSION[$type] as $user) : ?>
            <tr>
                <td><input type='checkbox' name='checkboxuser[]' value=<?= $user['id'] ?>></td>
                <td><?= $user['nickName'] ?></td>
                <td><?= $user['firstName'] ?></td>
                <td><?= $user['lastName'] ?></td>
                <td><?php if ($user['avatar'] && $user['avatar'] != "") : ?>
                        <img src=<?= $user['avatar'] ?> alt='avatar'>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>