   <div class="flex-around">
       <section>
           <p>Réseaux sociaux</p>
           <nav>
               <ul class="flex-around">
                   <li><a href="https://www.facebook.com/duportstephane" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
                   <li><a href="https://www.instagram.com/stephane.duport/" target="_blank"><i class="fab fa-instagram"></i></a></li>
                   <li><a href="https://github.com/Duport-Stephane/3WA-TournamentPoker" target="_blank"><i class="fab fa-github"></i></a></li>
                   <li><a href="https://www.linkedin.com/in/stéphane-duport-bab3a484" target="_blank"><i class="fab fa-linkedin-in"></i></a></li>
               </ul>
           </nav>
       </section>
       <section class="about">
           <p>A Propos</p>
           <nav>
               <ul class="flex-between">
                   <li><a href="../../src/controller/bonus.php" class="bonus">Bonus</a></li>
                   <li><a href="../../src/controller/rules.php" class="rules">Règles du poker</a></li>
                   <li><a href="../../src/controller/contact.php" class="contact">Contact</a></li>
               </ul>
               <!-- <a href="https://fr.pokernews.com/dictionnaire-poker/" target="_blank">Règles du poker</a> -->
           </nav>
       </section>
   </div>
   <p>
       <img src="../../asset/images/logo DS.png" alt="logo">DUPORT Stéphane - 2021
       <!-- <i class="far fa-copyright small"></i> -->
   </p>