    <div class="flex-around">
        <section>
            <p>Réseaux sociaux</p>
            <nav class="flex-between">
                <a><i class="fab fa-facebook-f"></i></a>
                <a><i class="fab fa-instagram"></i></a>
                <a><i class="fab fa-github"></i></a>
                <a><i class="fab fa-linkedin-in"></i></a>
            </nav>
        </section>
        <section>
            <p>A Propos</p>
            <nav class="flex-between">
                <a href="">Direction 1</a>
                <a href="">Direction 2</a>
                <a href="">Direction 3</a>
            </nav>
        </section>
    </div>
    <p>
        <img src="../../asset/images/logo DS.png" alt="logo">DUPORT Stéphane - 2021
        <!-- <i class="far fa-copyright small"></i> -->
    </p>