<div class="flex-around">
    <section>
        <p>Réseaux sociaux</p>
        <nav>
            <ul class="flex-around">
                <li><a href="https://www.facebook.com/duportstephane" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
                <li><a href="https://www.instagram.com/stephane.duport/" target="_blank"><i class="fab fa-instagram"></i></a></li>
                <li><a href="https://github.com/Duport-Stephane/3WA-TournamentPoker" target="_blank"><i class="fab fa-github"></i></a></li>
                <li><a href="https://www.linkedin.com/in/stéphane-duport-bab3a484" target="_blank"><i class="fab fa-linkedin-in"></i></a></li>
            </ul>
        </nav>
    </section>
    <section>
        <p>Navigation</p>
        <nav>
            <ul class="flex-between">
                <li><a href="./index.php?page=home" class='home'>Accueil</a></li>
                <li><a href="./index.php?page=bonus" class="bonus">Bonus</a></li>
                <li><a href="./index.php?page=rules" class="rules">Règles du poker</a></li>
                <li><a href="./index.php?page=contact" class="contact">Contact</a></li>
                <li>
                    <label id="theme-switch" class="theme-switch" for="checkbox_theme">Thème
                        <input type="checkbox" id="checkbox_theme">
                    </label>
                </li>

            </ul>
            <!-- <a href="https://fr.pokernews.com/dictionnaire-poker/" target="_blank">Règles du poker</a> -->
        </nav>
    </section>
</div>
<p>
    <img class="smallImg" src="./asset/images/logo DS.png" alt="logo">DUPORT Stéphane - 2021
    <!-- <i class="far fa-copyright small"></i> -->
</p>