<div class="navHeader flex-between headband">
    <nav>
        <ul class="flex-around">
            <li><a href="../../index.php" class='home'>Accueil</a></li>
            <li><a href="../../src/controller/players.php" class='players'>Players</a></li>
            <li><a href="../../src/controller/tables.php" class='tables'>Tables</a></li>
        </ul>
    </nav>
    <a href="../../src/controller/login.php" class="flex-column">
        <img src="../../asset/images/token/cyan.png" alt="login" class="token">
        <div class="small">Login</div>
    </a>
</div>

<h1 class="flex-center-items">
    <img src="../../asset/images/logo.png" alt="logo" class="token">Texas Hold'hem Tournament Poker
</h1>