<section class="navHeader flex-between headband">
    <nav>
        <ul class="flex-around">
            <li><a href="./index.php?page=home" class='home'>Accueil</a></li>
            <li><a href="./index.php?page=players&action=display" class='players'>Joueurs</a></li>
            <li><a href="./index.php?page=tables" class='tables'>Tables</a></li>
        </ul>
    </nav>
    <nav class="log">
        <ul class="flex-around">
            <?php if (\Models\Session::isOffsetExists('user') && \Models\Session::isConnected()) : ?>
                <li><a href="./index.php?page=logout" class="logout flex-column">
                        <img src="./asset/images/token/red.png" alt="logout" class="token">
                        <div class="small">Déconnexion</div>
                    </a></li>
            <?php else : ?>
                <li><a href="./index.php?page=inscription" class="inscription flex-column">
                        <img src="./asset/images/token/rose.png" alt="inscription" class="token">
                        <div class="small">Inscription</div>
                    </a></li>
                <li><a href="./index.php?page=login" class="login flex-column">
                        <img src="./asset/images/token/cyan.png" alt="login" class="token">
                        <div class="small">Connexion</div>
                    </a></li>
            <?php endif; ?>
        </ul>
    </nav>
</section>

<h1 class="flex-center-items headband">
    <img src="./asset/images/logo.png" alt="logo" class="token">Poker Hold'hem Tournament Poker
</h1>