<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="L'application 3W Tournament Poker permet de gérer une partie, un tournoi ou même un championnat de poker Texas Hold'hem. Créer votre partie en quelques clics, enregistrer les joueurs et lancer le chronomètre... Shuffle Up and Deal !">
<title>3W Tournament Poker</title>

<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Merienda:wght@400;700&family=Zilla+Slab:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<link rel="stylesheet" href="./asset/css/normalize.css" />
<link rel="stylesheet" href="./asset/css/style.css">
<link rel="shortcut icon" href="./asset/images/logo.ico">