<h1 class="flex-center-items headband">
    <img src="./asset/images/logo.png" alt="logo" class="token">Poker Hold'hem Tournament Poker
</h1>
<section class="navHeader flex-between headband">
    <nav>
        <ul class="flex-around">
            <li><a href="./index.php?page=home" class='home'>Accueil</a></li>
            <li><a href="./index.php?page=game" class='game'>Jeu</a></li>
            <li><a href="./index.php?page=players&action=display" class='players'>Joueurs</a></li>
        </ul>
    </nav>
    <nav class="log">
        <ul class="flex-around">
            <?php if (\Models\Session::isOffsetExists('user') && \Models\Session::isConnected()) : ?>
                <li><a id='logout' href="./index.php?page=logout" class="logout flex-column">
                        <img src="./asset/images/token/red.png" alt="logout" class="token">
                        <div class="small">Déconnexion</div>
                    </a></li>
                <?php if (\Models\Session::isOffsetExists('user') && (\Models\Session::getOffset1_Offset2('user', 'role_id') === '2')) : ?>
                    <li><a href="./index.php?page=dashboardUser" class="dashboardUser flex-column">
                            <img src="./asset/images/token/yellow.png" alt="dashboard User" class="token">
                            <div class="small"><?= \Models\Session::getOffset1_Offset2('user', 'nickName') ?></div>
                        </a></li>
                <?php elseif (\Models\Session::isOffsetExists('user') && ((\Models\Session::getOffset1_Offset2('user', 'role_id') === '1') || (\Models\Session::getOffset1_Offset2('user', 'role_id') === '5'))) : ?>
                    <li><a href="./index.php?page=dashboardAdmin" class="dashboardAdmin flex-column">
                            <img src="./asset/images/token/green.png" alt="dashboard Admin" class="token">
                            <div class="small"><?= \Models\Session::getOffset1_Offset2('user', 'nickName') ?></div>
                        </a></li>
                <?php endif; ?>
            <?php else : ?>
                <li><a href="./index.php?page=login" class="login flex-column">
                        <img src="./asset/images/token/cyan.png" alt="login" class="token">
                        <div class="small">Connexion</div>
                    </a></li>
                <li><a href="./index.php?page=inscription" class="inscription flex-column">
                        <img src="./asset/images/token/rose.png" alt="inscription" class="token">
                        <div class="small">Inscription</div>
                    </a></li>
            <?php endif; ?>
        </ul>
    </nav>
</section>