<?php if (\Models\Session::isOffsetExists('alert') && !empty(\Models\Session::getOffset('alert'))) : ?>
    <div id="notifAlert" class="alert alert-danger">
        <p><?= \Models\Session::getOffset('alert') ?></p>
    </div>
<?php endif; ?>

<?php if (\Models\Session::isOffsetExists('info') && !empty(\Models\Session::getOffset('info'))) : ?>
    <div id="notif" class="alert alert-info">
        <p><?= \Models\Session::getOffset('info') ?></p>
    </div>
<?php endif; ?>

<!-- To not display 2 times -->
<?php \Models\Session::unsetOffset('alert'); ?>
<?php \Models\Session::unsetOffset('info'); ?>