<!-- <h2 class="from-left">Liste des joueurs</h2> -->

<table class='array'>

    <h3><?= count($users) ?> Joueurs inscrits sur l'application</h3>
    <tr> 
        <th>​</th>
        <th>Pseudo</th>
        <th>Nom</th>
        <th>Prénom</th>
        <th>Avatar</th>
    </tr> 
</table>
<div class='array-border tabusersList'>
    <table class='array'>
        <?php foreach ($users as $user) : { ?>
                <tr>
                    <td><input type='checkbox' name='checkboxuser[]' value=<?= $user['id'] ?>></td>
                    <td class="selectUser <?= $user['id'] ?>"><?= $user['nickName'] ?></td>
                    <td class="selectUser <?= $user['id'] ?>"><?= $user['lastName'] ?></td>
                    <td class="selectUser <?= $user['id'] ?>"><?= $user['firstName'] ?></td>
                    <td><?php if ($user['avatar'] !== "") : { ?>
                                <img src=<?= $user['avatar'] ?> alt='avatar'>
                        <?php }
                        endif; ?>
                    </td>
                </tr>
        <?php }
        endforeach; ?>
    </table>
</div>
<!-- <input class="findUser card-search" type="text" name="findUser">Rechercher un joueur -->